services:
  #
  # RabbitMQ
  #
  rabbitmq:
    build: ./packages/rabbitmq
    container_name: rabbitmqcontainer
    ports:
      - 5672:5672
      - 15672:15672

  #
  # Service Shop + Datenbank
  #
  dbshop:
    build: ./packages/db_shop
    container_name: dbshopcontainer
    volumes:
      - /var/lib/mysql/shop:/dbdata
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop

  appshop:
    build: ./apps/Shop
    container_name: appshopcontainer
    ports:
      - 8081:8080
    volumes:
      - ./apps/Shop:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbshop:3306/shop
      SPRING_QUEUE_URL: rabbitmq
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DEVTOOLS_RESTART_ENABLED: true
    depends_on:
      - dbshop
      - rabbitmq

  #
  # Service Lager + Datenbank
  #
  dblager:
    build: ./packages/db_lager
    container_name: dblagercontainer
    volumes:
      - /var/lib/mysql/lager:/dbdata
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lager

  applager:
    build: ./apps/Lager
    container_name: applagercontainer
    ports:
      - 8082:8080
    volumes:
      - ./apps/Lager:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dblager:3306/lager
      SPRING_QUEUE_URL: rabbitmq
    depends_on:
      - dblager
      - rabbitmq
